version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./BookStore.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  client:
    build:
      context: .
      dockerfile: ./BookStore.Client/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api