# Netlify configuration for Blazor WebAssembly deployment
[build]
  publish = "BookStore.Client/bin/Release/net9.0/publish/wwwroot"
  command = "bash build-netlify.sh"

[build.environment]
  DOTNET_VERSION = "9.0.100"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
