# Railway configuration for .NET application

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = [
  "dotnet restore BookStore.Api/BookStore.Api.csproj",
  "dotnet publish BookStore.Api/BookStore.Api.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/BookStore.Api.dll"
